language: java

sudo: false

matrix:
  include:
   - os: linux
     jdk: oraclejdk8
     addons:
       apt:
         packages:
           - gcc-multilib
   - os: linux
     # Travis by default is 64 bit so we toggle to use the 32 bit libs
     env: MAVEN_PROFILE="-DosDetection=false -Plinux-x86_32"
     jdk: oraclejdk8
     addons:
       apt:
         packages:
           - cmake
           - gcc-multilib
   # xcode8 maps to oraclejdk8: https://github.com/travis-ci/travis-ci/issues/2316
   - os: osx
     osx_image: xcode8.1

install: true
script:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw -V install $MAVEN_PROFILE

notifications:
  irc:
    channels:
      - irc.freenode.org#freelibrary
    on_failure: always
    on_success: always
  email:
    recipients:
      - ksclarke@ksclarke.io
    on_failure: change
    on_success: change
