# Source: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven
name: Deploy to Maven Central
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  # One can look up a project's profileId by running:
  # mvn nexus-staging:rc-list-profiles -DserverId=maven-central-releases -DnexusUrl=https://oss.sonatype.org/
  STAGING_PROFILE_ID: "1a35794454094c"
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
  MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
jobs:
  open-release:
    runs-on: ubuntu-latest
    outputs:
      INITIAL_REF_POSITION: ${{ steps.open-staging.outputs.INITIAL_REF_POSITION }}
      TAG: ${{ steps.open-staging.outputs.TAG }}
      STAGING_REPOSITORY_ID: ${{ steps.open-staging.outputs.STAGING_REPOSITORY_ID }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          server-id: maven-central-releases
          # Server authentication corresponds to "user token" returned by https://oss.sonatype.org/
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          # Avoid caching generated artifacts
          path: |
            ~/.m2/repository/*
            !~/.m2/repository/com/googlecode/cmake-maven-project
          key: ${{ runner.OS }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.OS }}-maven-

      - name: Configure Git User
        run: |
          git config user.email "cowwoc2020@gmail.com"
          git config user.name "Gili Tzabari"

      # Maven command-line options:
      # --batch-mode: recommended in CI to inform maven to not run in interactive mode (less logs)
      # -V: strongly recommended in CI, will display the JDK and Maven versions in use.
      #      Very useful to be quickly sure the selected versions were the ones you think.
      # -e: Display stack-traces on failure
      #
      # Getting the current git tag: https://stackoverflow.com/a/50465671/14731
      #
      # Setting a GitHub Action output parameter:
      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
      #
      # "release:prepare" must skip integration tests because "binaries-on-path-test" requires artifacts
      # to be deployed to local repository.
      - name: Open staging repository
        id: open-staging
        run: |
          echo "INITIAL_REF_POSITION=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          ./mvnw release:prepare --batch-mode -V -e -Darguments="-Ddeploy -Dinvoker.skip=true"
          echo "TAG=$(git describe --tag --abbrev=0)" >> $GITHUB_OUTPUT
          
          output=$(./mvnw --batch-mode -e -DstagingProfileId=${{ env.STAGING_PROFILE_ID }} nexus-staging:rc-open)
          [[ "$output" =~ Opened\ (comgooglecodecmake-maven-project-[[:digit:]]+) ]]
          stagingRepositoryId="${BASH_REMATCH[1]}"
          echo "STAGING_REPOSITORY_ID=$stagingRepositoryId" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy (${{ matrix.os }})
    needs: open-release
    strategy:
      # Concurrent deploys of the files that are common across platforms may lead to data corruption
      max-parallel: 1
      matrix:
        runtime: [ linux-x64, linux-arm64, linux-arm, win-x64, osx-x64, osx-arm64, win-arm64 ]
        include:
          - runtime: linux-x64
            os: ubuntu-latest

          - runtime: linux-arm64
            os: ubuntu-latest

          - runtime: linux-arm
            os: ubuntu-latest

          - runtime: osx-x64
            os: macOS-latest

          - runtime: osx-arm64
            os: macOS-latest

          - runtime: win-x64
            os: windows-latest

          - runtime: win-arm64
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ needs.open-release.outputs.TAG }}
    - uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 8
        server-id: maven-central-releases
        # Server authentication corresponds to "user token" returned by https://oss.sonatype.org/
        server-username: OSSRH_USERNAME
        server-password: OSSRH_TOKEN
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Cache Dependencies
      uses: actions/cache@v3
      with:
        # Avoid caching generated artifacts
        path: |
          ~/.m2/repository/*
          !~/.m2/repository/com/googlecode/cmake-maven-project
        key: ${{ runner.OS }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.OS }}-maven-

    - name: Deploy to Maven Central
      run: >
        ./mvnw --batch-mode -V -e -Ddeploy -Dportable -DstagingProfileId=${{ env.STAGING_PROFILE_ID }}
        -DstagingRepositoryId=${{ needs.open-release.outputs.STAGING_REPOSITORY_ID }}
        deploy

  close-release:
    needs: [ open-release, deploy ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.open-release.outputs.TAG }}
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          server-id: maven-central-releases
          # Server authentication corresponds to "user token" returned by https://oss.sonatype.org/
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          # Avoid caching generated artifacts
          path: |
            ~/.m2/repository/*
            !~/.m2/repository/com/googlecode/cmake-maven-project
          key: ${{ runner.OS }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.OS }}-maven-

      - name: Close staging repository
        run: >
          ./mvnw --batch-mode -V -e -DstagingProfileId=${{ env.STAGING_PROFILE_ID }}
          -DstagingRepositoryId=${{ needs.open-release.outputs.STAGING_REPOSITORY_ID }}
          nexus-staging:rc-close

  # Cleanup on failure: https://stackoverflow.com/a/74562058/14731
  on-failure:
    needs: [ open-release, deploy, close-release ]
    runs-on: ubuntu-latest
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8
          server-id: maven-central-releases
          # Server authentication corresponds to "user token" returned by https://oss.sonatype.org/
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          # Avoid caching generated artifacts
          path: |
            ~/.m2/repository/*
            !~/.m2/repository/com/googlecode/cmake-maven-project
          key: ${{ runner.OS }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.OS }}-maven-

      - name: Configure Git User
        run: |
          git config user.email "cowwoc2020@gmail.com"
          git config user.name "Gili Tzabari"

      - name: Restore the workflow ref to its original position
        if: needs.open-release.outputs.INITIAL_REF_POSITION != ''
        run: |
          CURRENT_REF_POSITION=$(git rev-parse HEAD)
          if [ "${CURRENT_REF_POSITION}" != "${{ needs.open-release.outputs.INITIAL_REF_POSITION }}" ]; then
            git reset --hard ${{ needs.open-release.outputs.INITIAL_REF_POSITION }}
            if [ "${{ github.ref_type }}" == "tag" ]; then
              git ${{ github.ref_type }} -f ${{ github.ref_name }}
            fi
            git push -f origin ${{ github.ref_name }}
          fi

      - name: Delete tag
        if: needs.open-release.outputs.TAG != ''
        run: |
          git push --delete origin ${{ needs.open-release.outputs.TAG }}

      - name: Drop staging repository
        if: needs.open-release.outputs.STAGING_REPOSITORY_ID != ''
        run: >
          ./mvnw --batch-mode -V -e -DstagingProfileId=${{ env.STAGING_PROFILE_ID }}
          -DstagingRepositoryId=${{ needs.open-release.outputs.STAGING_REPOSITORY_ID }}
          nexus-staging:rc-drop