name: Deploy to Maven Central
on: workflow_dispatch
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
permissions:
  contents: write
  id-token: write

env:
  STAGING_HOST: "central.sonatype.com"
  MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
jobs:
  bearer-token:
    name: Generate Bearer Token
    runs-on: ubuntu-latest
    outputs:
      VALUE: ${{ steps.generate.outputs.VALUE }}
    steps:
      - id: generate
        # The credentials correspond to the user token returned by https://central.sonatype.com/account
        # See https://central.sonatype.org/publish/publish-portal-api/#authentication-authorization
        run: |
          echo "VALUE=$(printf "${{ secrets.MAVEN_CENTRAL_USERNAME }}:${{ secrets.MAVEN_CENTRAL_PASSWORD }}" \
          | base64)" >> "$GITHUB_OUTPUT"

  tag-release:
    name: Tag release
    runs-on: ubuntu-latest
    outputs:
      INITIAL_REF_POSITION: ${{ steps.create-tag.outputs.INITIAL_REF_POSITION }}
      TAG: ${{ steps.create-tag.outputs.TAG }}
      VERSION: ${{ steps.create-tag.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/*
          key: "${{ runner.OS }}-maven-${{ hashFiles('**/pom.xml') }}"

      - name: Configure Git User
        run: |
          git config user.email "cowwoc2020@gmail.com"
          git config user.name "Gili Tzabari"

      - name: Create tag
        id: create-tag
        run: |
          echo "INITIAL_REF_POSITION=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
          
          # Maven command-line options:
          # --batch-mode: recommended in CI to inform maven to not run in interactive mode (less logs)
          # -V: strongly recommended in CI, will display the JDK and Maven versions in use.
          #      Very useful to be quickly sure the selected versions were the ones you think.
          # -e: Display stack-traces on failure
          #
          # "release:prepare" must skip integration tests because "binaries-on-path-test" requires artifacts
          # to be deployed to local repository.
          ./mvnw release:prepare --batch-mode -V -e -Darguments="-Dinvoker.skip=true"
          
          # Getting the current git tag: https://stackoverflow.com/a/50465671/14731
          TAG=$(git describe --tag --abbrev=0)
          
          # Setting a GitHub Action output parameter:
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
          echo "TAG=${TAG}" >> "$GITHUB_OUTPUT"

          # Extracting the release version number: https://stackoverflow.com/a/16623897/14731
          echo "VERSION=${TAG#"release-"}" >> "$GITHUB_OUTPUT"

  build:
    needs: tag-release
    name: Build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    permissions:
      contents: read
      actions: read
      checks: write
    with:
      COMMIT_ID: ${{ needs.tag-release.outputs.TAG }}
      FOR_RELEASE: true
  deploy:
    needs: [ bearer-token, build ]
    name: Deploy
    runs-on: linux-x64
    outputs:
      ID: ${{ steps.upload.outputs.ID }}
    steps:
      - name: Download bundles
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: "${GITHUB_WORKSPACE}/bundles"

      - name: Merge bundles
        run: |
          mkdir merge
          cd merge
          
          unzip ../bundles/*.zip
          ls -laR .
          zip -r "../cmake-maven-plugin-${{ needs.tag-release.outputs.VERSION }}.zip"

      - name: Upload bundle
        id: upload
        run: |
          ID=$(curl --request POST --verbose --show-error --fail \
          --header "Authorization: Bearer ${{ needs.bearer-token.outputs.VALUE }}" \
          --form "bundle=@cmake-maven-plugin-${{ needs.tag-release.outputs.VERSION }}.zip" \
          --form "name=cmake-maven-plugin-${{ needs.tag-release.outputs.VERSION }}" \
          --form "publishingType=USER_MANAGED" \
          https://central.sonatype.com/api/v1/publisher/upload)
          
          echo "ID=${ID}" >> $GITHUB_ENV

      - name: Poll for deployment status
        run: |
          while true; do
            response=$(curl --request POST --verbose --show-error --fail \
            --header "Authorization: Bearer ${{ needs.bearer-token.outputs.VALUE }}" \
            "https://central.sonatype.com/api/v1/publisher/status?id=${{ steps.upload.outputs.ID }}")

            status=$(echo "${response}" | jq -r '.deploymentState')
            echo "Current status: ${status}"
          
            if [[ "${status}" == "VALIDATED" ]]; then
              echo "Deployment validated successfully!"
              exit 0
            elif [[ "${status}" == "FAILED" ]]; then
              echo "Deployment failed!"
              exit 1
            fi
            sleep 5
          done
  on-failure:
    name: On failure
    needs: [ bearer-token, tag-release, deploy ]
    runs-on: ubuntu-latest
    if: ${{ failure() || cancelled() }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8

      - name: Drop the bundle
        if: needs.deploy.outputs.ID != ''
        run: >
          curl --request DELETE --verbose --show-error --fail \
            --header "Authorization: Bearer ${{ needs.bearer-token.outputs.VALUE }}" \
            "https://central.sonatype.com/api/v1/publisher/status?id=${{ needs.deploy.outputs.ID }}")

      - name: Restore the workflow ref to its original position
        if: needs.tag-release.outputs.INITIAL_REF_POSITION != ''
        run: |
          CURRENT_REF_POSITION=$(git rev-parse HEAD)
          if [ "${CURRENT_REF_POSITION}" != "${{ needs.tag-release.outputs.INITIAL_REF_POSITION }}" ]; then
            git reset --hard ${{ needs.tag-release.outputs.INITIAL_REF_POSITION }}
            if [ "${{ github.ref_type }}" == "tag" ]; then
              git ${{ github.ref_type }} -f ${{ github.ref_name }}
            fi
            git push -f origin ${{ github.ref_name }}
          fi

      - name: Delete tag
        if: needs.tag-release.outputs.TAG != ''
        run: |
          git push --delete origin ${{ needs.tag-release.outputs.TAG }}